#!/bin/bash
# .cursor/hooks/after-file-edit.sh
# 🌸 Real-time Auto-Correction Detection Hook
# Called after AI edits a file - automatically detects corrections and learns patterns

set -e

# Read input JSON from Cursor
INPUT=$(cat)

# Extract file path and workspace
FILE_PATH=$(echo "$INPUT" | jq -r '.file_path // empty')
WORKSPACE=$(echo "$INPUT" | jq -r '.workspace_roots[0] // .workspace // empty')

# Skip if no file path or workspace
if [ -z "$FILE_PATH" ] || [ -z "$WORKSPACE" ]; then
    # Silent skip - no need to log
    exit 0
fi

# Only process files that were generated by Lulu (have tracked generations)
# Check if .lulu/generations.json or .lulu/learning.enc exists
GENERATIONS_FILE="$WORKSPACE/.lulu/generations.json"
LEARNING_FILE="$WORKSPACE/.lulu/learning.enc"

if [ ! -f "$GENERATIONS_FILE" ] && [ ! -f "$LEARNING_FILE" ]; then
    # No generations tracked yet, skip silently
    exit 0
fi

# Check if this file has been tracked (quick check)
FILE_RELATIVE=$(echo "$FILE_PATH" | sed "s|^$WORKSPACE/||" | sed "s|^\./||")
if [ -f "$GENERATIONS_FILE" ]; then
    if ! grep -q "\"file\":\"$FILE_RELATIVE\"" "$GENERATIONS_FILE" 2>/dev/null; then
        # File not tracked, skip silently
        exit 0
    fi
fi

# Log detection start (minimal output)
echo "[LULU] 🔍 Auto-detecting corrections..." >&2

# Track operation start time for cost logging
HOOK_START_TIME=$(date +%s%3N)

# Call lulu learn command (quietly) to detect corrections
# This will:
# 1. Detect what changed from tracked generations
# 2. Update learned patterns automatically
# 3. Update cursor rules if confidence is high (≥80% with 3+ occurrences)
cd "$WORKSPACE" || exit 0

# Try lulu CLI first
if command -v lulu >/dev/null 2>&1; then
    # Run lulu learn quietly (suppress all output unless critical errors)
    lulu learn --quiet >/dev/null 2>&1 && {
        echo "[LULU] ✅ Corrections detected and patterns updated" >&2
        
        # Log cost (correction detection is local, but track operation)
        HOOK_END_TIME=$(date +%s%3N)
        HOOK_DURATION=$((HOOK_END_TIME - HOOK_START_TIME))
        
        # Log to cost file if it exists (via MCP if available, or create simple log)
        if [ -f ".lulu/operations-cost.log" ]; then
            echo "{\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"operation\":\"correction_detection\",\"tool\":\"after-file-edit-hook\",\"filePath\":\"$FILE_RELATIVE\",\"estimatedTokens\":{\"input\":0,\"output\":0},\"estimatedCost\":0,\"model\":\"local\",\"duration\":$HOOK_DURATION,\"metadata\":{\"hook\":\"after-file-edit\",\"file\":\"$FILE_RELATIVE\"}}" >> .lulu/operations-cost.log 2>/dev/null || true
        fi
    } || {
        # Silent failure - don't spam user
        true
    }
elif [ -f "package.json" ] && grep -q '"lulu"' package.json; then
    # Fallback: Try npm run lulu learn if lulu CLI not in PATH
    npm run lulu learn --quiet >/dev/null 2>&1 || true
elif [ -f "node_modules/.bin/lulu" ]; then
    # Fallback: Use local lulu binary
    ./node_modules/.bin/lulu learn --quiet >/dev/null 2>&1 || true
fi

# No output needed - observational hook
exit 0
